<a href="https://colab.research.google.com/github/unmei211/machine-learning/blob/main/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


2) Создать нулевой вектор размера 10

In [ ]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
arr = np.linspace(7,7,7)
print(arr)

[7. 7. 7. 7. 7. 7. 7.]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,101)[::2]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
np.random.random_sample(5)[::-1]

array([0.48712502, 0.57739232, 0.02833476, 0.92015574, 0.87571361])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
arr = np.arange(9)
matrix = arr.reshape(3,3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4,k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix = np.full((4,4),7)
print(np.fill_diagonal(matrix, [1,2,3,4]))
print(matrix)

None
[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.full((5,5), [0,1,2,3,4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
matrix = np.random.random_sample((10,10))


array([[0.19095188, 0.8170565 , 0.15690112, 0.52198227, 0.58371583,
        0.74107376, 0.1678442 , 0.00823602, 0.83712484, 0.84271432],
       [0.54863215, 0.4485761 , 0.62785419, 0.47918418, 0.6565623 ,
        0.92157576, 0.29986886, 0.18485086, 0.08163529, 0.74885698],
       [0.86056796, 0.56237078, 0.72222341, 0.67418833, 0.36219529,
        0.68370834, 0.02210038, 0.43456746, 0.00590929, 0.53756226],
       [0.67505794, 0.80301971, 0.30294461, 0.5744923 , 0.57720304,
        0.47214329, 0.16955843, 0.33202249, 0.10449689, 0.23409886],
       [0.25821472, 0.15285139, 0.11374887, 0.04598685, 0.2174706 ,
        0.10630414, 0.21537822, 0.88120275, 0.50688174, 0.78779855],
       [0.3630453 , 0.65092949, 0.86468063, 0.32308947, 0.88209825,
        0.27426342, 0.04387498, 0.73387545, 0.15109646, 0.95669477],
       [0.08017101, 0.16807612, 0.5250877 , 0.16472651, 0.28459752,
        0.26989774, 0.95188359, 0.43735022, 0.10721525, 0.1781172 ],
       [0.68316222, 0.11267507, 0.2696442

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.